[2020-10-22T17:19:23-0700] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host drkthomp-virtualbox.
[2020-10-22T17:19:23-0700] [MainThread] [I] [toil.leader] Issued job 'parse_config_file' kind-parse_config_file/instance-s_nr25h6 with job batch system ID: 0 and cores: 1, disk: 2.0 G, and memory: 2.0 G
[2020-10-22T17:19:23-0700] [MainThread] [I] [toil.worker] Redirecting logging to /home/drkthomp/workDir/node-f1f8997a-f8d2-4f90-ad06-953f95d5bcdd-1e53f69f16d74e0b881e7db602b2d2c3/tmpsa5trpov/worker_log.txt
[2020-10-22T17:19:24-0700] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker parse_config_file file:/home/drkthomp/protect3/jobStore kind-parse_config_file/instance-s_nr25h6.
[2020-10-22T17:19:24-0700] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'parse_config_file' kind-parse_config_file/instance-s_nr25h6
[2020-10-22T17:19:24-0700] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'parse_config_file' kind-parse_config_file/instance-s_nr25h6
[2020-10-22T17:19:24-0700] [MainThread] [W] [toil.leader] Log from job kind-parse_config_file/instance-s_nr25h6 follows:
=========>
	[2020-10-22T17:19:23-0700] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2020-10-22T17:19:23-0700] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host drkthomp-virtualbox.
	[2020-10-22T17:19:23-0700] [MainThread] [I] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Parsing config file
	/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py:334: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  input_config = yaml.load(conf.read())
	/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py:339: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  required_keys = yaml.load(ref.read())
	/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py:351: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  protect_defaults = yaml.load(pdf.read())
	Traceback (most recent call last):
	  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/worker.py", line 368, in workerScript
	    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/job.py", line 1424, in _runner
	    returnValues = self._run(jobGraph, fileStore)
	  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/job.py", line 1361, in _run
	    return self.run(fileStore)
	  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/job.py", line 1565, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py", line 444, in parse_config_file
	    sample_set, univ_options, processed_tool_inputs = _parse_config_file(job, config_file,
	  File "/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py", line 363, in _parse_config_file
	    _ensure_patient_group_is_ok(patient_keys, sample_name)
	  File "/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py", line 120, in _ensure_patient_group_is_ok
	    raise ParameterError(('The patient entry for sample %s ' % patient_name) +
	protect.common.ParameterError: The patient entry for sample TEST does not contain a hla_haplotype_files entry.
	Cannot haplotype patient if all the input sequence files are not fastqs.
	[2020-10-22T17:19:23-0700] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host drkthomp-virtualbox
<=========
[2020-10-22T17:19:24-0700] [MainThread] [W] [toil.jobGraph] Due to failure we are reducing the remaining retry count of job 'parse_config_file' kind-parse_config_file/instance-s_nr25h6 with ID kind-parse_config_file/instance-s_nr25h6 to 1
[2020-10-22T17:19:24-0700] [MainThread] [I] [toil.leader] 0 jobs are running, 0 jobs are issued and waiting to run
[2020-10-22T17:19:24-0700] [MainThread] [I] [toil.leader] Issued job 'parse_config_file' kind-parse_config_file/instance-s_nr25h6 with job batch system ID: 1 and cores: 1, disk: 2.0 G, and memory: 2.0 G
[2020-10-22T17:19:24-0700] [MainThread] [I] [toil.worker] Redirecting logging to /home/drkthomp/workDir/node-f1f8997a-f8d2-4f90-ad06-953f95d5bcdd-1e53f69f16d74e0b881e7db602b2d2c3/tmpyy3gjlcr/worker_log.txt
[2020-10-22T17:19:24-0700] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker parse_config_file file:/home/drkthomp/protect3/jobStore kind-parse_config_file/instance-s_nr25h6.
[2020-10-22T17:19:24-0700] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'parse_config_file' kind-parse_config_file/instance-s_nr25h6
[2020-10-22T17:19:24-0700] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'parse_config_file' kind-parse_config_file/instance-s_nr25h6
[2020-10-22T17:19:24-0700] [MainThread] [W] [toil.leader] Log from job kind-parse_config_file/instance-s_nr25h6 follows:
=========>
	[2020-10-22T17:19:24-0700] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2020-10-22T17:19:24-0700] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host drkthomp-virtualbox.
	[2020-10-22T17:19:24-0700] [MainThread] [I] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Parsing config file
	/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py:334: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  input_config = yaml.load(conf.read())
	/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py:339: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  required_keys = yaml.load(ref.read())
	/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py:351: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  protect_defaults = yaml.load(pdf.read())
	Traceback (most recent call last):
	  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/worker.py", line 368, in workerScript
	    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/job.py", line 1424, in _runner
	    returnValues = self._run(jobGraph, fileStore)
	  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/job.py", line 1361, in _run
	    return self.run(fileStore)
	  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/job.py", line 1565, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py", line 444, in parse_config_file
	    sample_set, univ_options, processed_tool_inputs = _parse_config_file(job, config_file,
	  File "/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py", line 363, in _parse_config_file
	    _ensure_patient_group_is_ok(patient_keys, sample_name)
	  File "/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py", line 120, in _ensure_patient_group_is_ok
	    raise ParameterError(('The patient entry for sample %s ' % patient_name) +
	protect.common.ParameterError: The patient entry for sample TEST does not contain a hla_haplotype_files entry.
	Cannot haplotype patient if all the input sequence files are not fastqs.
	[2020-10-22T17:19:24-0700] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host drkthomp-virtualbox
<=========
[2020-10-22T17:19:24-0700] [MainThread] [W] [toil.jobGraph] Due to failure we are reducing the remaining retry count of job 'parse_config_file' kind-parse_config_file/instance-s_nr25h6 with ID kind-parse_config_file/instance-s_nr25h6 to 0
[2020-10-22T17:19:24-0700] [MainThread] [W] [toil.leader] Job 'parse_config_file' kind-parse_config_file/instance-s_nr25h6 with ID kind-parse_config_file/instance-s_nr25h6 is completely failed
[2020-10-22T17:19:28-0700] [MainThread] [I] [toil.leader] Finished toil run with 1 failed jobs.
[2020-10-22T17:19:28-0700] [MainThread] [I] [toil.leader] Failed jobs at end of the run: 'parse_config_file' kind-parse_config_file/instance-s_nr25h6
Traceback (most recent call last):
  File "/home/drkthomp/protect3/venv/bin/ProTECT", line 33, in <module>
    sys.exit(load_entry_point('protect', 'console_scripts', 'ProTECT')())
  File "/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py", line 1026, in main
    Job.Runner.startToil(start, params)
  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/job.py", line 796, in startToil
    return toil.start(job)
  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/common.py", line 846, in start
    return self._runMainLoop(rootJobGraph)
  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/common.py", line 1133, in _runMainLoop
    return Leader(config=self.config,
  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/leader.py", line 269, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException: The job store 'file:/home/drkthomp/protect3/jobStore' contains 1 failed jobs: 'parse_config_file' kind-parse_config_file/instance-s_nr25h6
Log from job 'parse_config_file' kind-parse_config_file/instance-s_nr25h6 follows:
=========>
	[2020-10-22T17:19:24-0700] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2020-10-22T17:19:24-0700] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host drkthomp-virtualbox.
	[2020-10-22T17:19:24-0700] [MainThread] [I] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Parsing config file
	/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py:334: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  input_config = yaml.load(conf.read())
	/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py:339: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  required_keys = yaml.load(ref.read())
	/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py:351: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
	  protect_defaults = yaml.load(pdf.read())
	Traceback (most recent call last):
	  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/worker.py", line 368, in workerScript
	    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/job.py", line 1424, in _runner
	    returnValues = self._run(jobGraph, fileStore)
	  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/job.py", line 1361, in _run
	    return self.run(fileStore)
	  File "/home/drkthomp/protect3/venv/lib/python3.8/site-packages/toil/job.py", line 1565, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py", line 444, in parse_config_file
	    sample_set, univ_options, processed_tool_inputs = _parse_config_file(job, config_file,
	  File "/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py", line 363, in _parse_config_file
	    _ensure_patient_group_is_ok(patient_keys, sample_name)
	  File "/home/drkthomp/protect3/src/protect/pipeline/ProTECT.py", line 120, in _ensure_patient_group_is_ok
	    raise ParameterError(('The patient entry for sample %s ' % patient_name) +
	protect.common.ParameterError: The patient entry for sample TEST does not contain a hla_haplotype_files entry.
	Cannot haplotype patient if all the input sequence files are not fastqs.
	[2020-10-22T17:19:24-0700] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host drkthomp-virtualbox
<=========
